/* ═══════════════════════════════════════════════════════════
   TAPE DECK — the playlist

   GENERATED by `npm run tape` from the files in public/music/.
   Titles and artists come from each file's ID3 tags.

   The `note` on each track is the part that matters — one line on
   why the song is on the tape. Edit those here; re-running the
   script keeps them. An empty note simply renders nothing.
   ═══════════════════════════════════════════════════════════ */

export interface Track {
  title: string
  artist: string
  /** Path under public/, which Vite serves from the site root. */
  file: string
  /** Why this one is on the tape. Shown in the Music window. */
  note: string
}

export const PLAYLIST: Track[] = [
  {
    title: "Dhun",
    artist: "Arijit Singh",
    file: "/music/01-dhun.mp3",
    note: "",
  },
  {
    title: "Hoor",
    artist: "Samar Jafri",
    file: "/music/02-hoor.mp3",
    note: "",
  },
  {
    title: "Khat",
    artist: "Navjot Ahuja",
    file: "/music/03-khat.mp3",
    note: "",
  },
  {
    title: "O Soniye",
    artist: "Arijit Singh, Vibha Saraf",
    file: "/music/04-o-soniye.mp3",
    note: "",
  },
  {
    title: "Rakhlo Tum Chupaake",
    artist: "Arpit Bala",
    file: "/music/05-rakhlo-tum-chupaake.mp3",
    note: "",
  },
]

/** Shown in the Music window when a file hasn't been added yet. */
export const MISSING_NOTE =
  "This one isn't on the tape yet. Hassan had ten days and chose to do other things."
