/* ═══════════════════════════════════════════════════════════
   npm run tape

   Scans public/music/, reads the ID3 tags off every audio file,
   and rewrites src/content/music.ts to match.

   Any `note` you have already written is carried over — matched
   by filename, so renaming a file loses its note but reordering
   or re-tagging does not.
   ═══════════════════════════════════════════════════════════ */
import { readdir, readFile, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join, basename, extname } from "node:path"
import { parseFile } from "music-metadata"

const MUSIC_DIR = "public/music"
const TARGET = "src/content/music.ts"
const AUDIO = new Set([".mp3", ".m4a", ".ogg", ".opus", ".wav", ".flac"])

/** Pull the existing notes out of music.ts so hand-written ones survive. */
async function existingNotes() {
  if (!existsSync(TARGET)) return {}
  const src = await readFile(TARGET, "utf8")
  const notes = {}
  /* Entries are written title → artist → file → note, so `file` always
     precedes the `note` it belongs to. */
  const re = /file:\s*"([^"]+)"[\s\S]*?note:\s*"((?:[^"\\]|\\.)*)"/g
  let m
  while ((m = re.exec(src))) notes[basename(m[1])] = m[2]
  return notes
}

function title(str) {
  return str.replace(/^\d+[\s._-]*/, "").replace(/_/g, " ").trim()
}

const notes = await existingNotes()

if (!existsSync(MUSIC_DIR)) {
  console.error(`✗ ${MUSIC_DIR} does not exist.`)
  process.exit(1)
}

const files = (await readdir(MUSIC_DIR))
  .filter((f) => AUDIO.has(extname(f).toLowerCase()))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

if (!files.length) {
  console.error(`✗ No audio files in ${MUSIC_DIR}/. Drop the mp3s in and run again.`)
  process.exit(1)
}

const tracks = []
let missingNotes = 0

for (const f of files) {
  let tag = {}
  let seconds = 0
  try {
    const meta = await parseFile(join(MUSIC_DIR, f), { duration: true })
    tag = meta.common ?? {}
    seconds = Math.round(meta.format?.duration ?? 0)
  } catch {
    console.warn(`  ! could not read tags from ${f} — falling back to the filename`)
  }

  /* An unwritten note is an empty string — the UI then renders nothing rather
     than showing her a placeholder. Legacy TODO text counts as unwritten. */
  const found = notes[f] ?? ""
  const note = /^TODO/i.test(found) ? "" : found
  if (!note.trim()) missingNotes++

  tracks.push({
    title: tag.title?.trim() || title(basename(f, extname(f))),
    artist: tag.artist?.trim() || "—",
    file: `/music/${f}`,
    note,
  })

  const mins = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`
  console.log(`  ${String(tracks.length).padStart(2, "0")}  ${tracks[tracks.length - 1].title} — ${tracks[tracks.length - 1].artist}  (${mins})`)
}

const body = tracks
  .map(
    (t) => `  {
    title: ${JSON.stringify(t.title)},
    artist: ${JSON.stringify(t.artist)},
    file: ${JSON.stringify(t.file)},
    note: ${JSON.stringify(t.note)},
  },`,
  )
  .join("\n")

await writeFile(
  TARGET,
  `/* ═══════════════════════════════════════════════════════════
   TAPE DECK — the playlist

   GENERATED by \`npm run tape\` from the files in public/music/.
   Titles and artists come from each file's ID3 tags.

   The \`note\` on each track is the part that matters — one line on
   why the song is on the tape. Edit those here; re-running the
   script keeps them. An empty note simply renders nothing.
   ═══════════════════════════════════════════════════════════ */

export interface Track {
  title: string
  artist: string
  /** Path under public/, which Vite serves from the site root. */
  file: string
  /** Why this one is on the tape. Shown in the Music window. */
  note: string
}

export const PLAYLIST: Track[] = [
${body}
]

/** Shown in the Music window when a file hasn't been added yet. */
export const MISSING_NOTE =
  "This one isn't on the tape yet. Hassan had ten days and chose to do other things."
`,
  "utf8",
)

console.log(`\n✓ ${tracks.length} track${tracks.length === 1 ? "" : "s"} written to ${TARGET}`)
if (missingNotes) console.log(`  ${missingNotes} still need a note.`)
